version: "2"

services:
  mongo:
    image: mongo:4.0.6
    restart: always
    volumes:
      - ./storage:/data/db
      - ./conf:/etc/mongo
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./log:/var/log/mongodb
    ports:
      - "30010:27017"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - backend

networks:
  backend:
    driver: overlay
